// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrackingService.API.Database;

namespace TrackingService.API.Migrations
{
    [DbContext(typeof(TrackingDbContext))]
    [Migration("20210330011511_FixedPrecision")]
    partial class FixedPrecision
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tracking")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("TrackingService.Model.Objects.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Imei")
                        .HasColumnType("text")
                        .HasColumnName("imei");

                    b.Property<int>("LastPositionId")
                        .HasColumnType("integer")
                        .HasColumnName("last_position_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("Imei")
                        .HasDatabaseName("ix_devices_imei");

                    b.ToTable("devices");
                });

            modelBuilder.Entity("TrackingService.Model.Objects.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<float>("Direction")
                        .HasColumnType("float(2)")
                        .HasColumnName("direction");

                    b.Property<string>("Imei")
                        .HasColumnType("text")
                        .HasColumnName("imei");

                    b.Property<float>("Lat")
                        .HasColumnType("float(6)")
                        .HasColumnName("lat");

                    b.Property<float>("Lon")
                        .HasColumnType("float(6)")
                        .HasColumnName("lon");

                    b.Property<string>("MiscInfo")
                        .HasColumnType("text")
                        .HasColumnName("misc_info");

                    b.Property<string>("Protocol")
                        .HasColumnType("text")
                        .HasColumnName("protocol");

                    b.Property<float>("Speed")
                        .HasColumnType("float(2)")
                        .HasColumnName("speed");

                    b.HasKey("Id")
                        .HasName("pk_positions");

                    b.HasIndex("Imei")
                        .HasDatabaseName("ix_positions_imei");

                    b.ToTable("positions");
                });
#pragma warning restore 612, 618
        }
    }
}
